### PR TITLE
Added flux queries compatibility

### PR DESCRIPTION
**Pull request by toni-moreno**
now we can config a "pass-through" flux endpoint 

```toml
 [[http.endpoint]]
    uri=["/api/v2/query"]
    type="RD"
    source_format="IQL"

    [[http.endpoint.route]]
      name="pass_thougth"
      level="http" # http or data
      log-inherit = true
      log-level = "debug"

      [[http.endpoint.route.filter]]
        name="pass_all"
        key="db" #availabe http params
        match=".*"

      [[http.endpoint.route.rule]]
        name="pass_all"
        action="route"
        key="db"
        match=".*"
        to_cluster="cluster_linux"
```

### CODE REVIEW

**Comment by jcdauchy-moodys** [comment]
Hello Toni, was wondering if this PR (and corresponding branch) is working ? 
I would like to test out the Flux compatibility. Do you need to add functionnalities or it is just a matter of time to merge this PR ?

Thanks, first tests on K8s seems to be fine. Great work.
Christophe

**Comment by toni-moreno** [comment]
Hello @jcdauchy-moodys , I have plans in next weeks, but not sure exactly when. sorry not much time to spent on this issue (yet), and I need to add a few things before this PR could be merged.

**Comment by jcdauchy-moodys** [comment]
Ok thanks for the quick replay. If i try to test it. It should mainly work, i guess.

**Comment by muscatmat** [comment]
Hi @toni-moreno, I really require this feature and was wondering if this PR will be merged?

Thanks a million and waiting for your reply,
Matthew Muscat

**Comment by toni-moreno** [comment]
@muscatmat done !

**Pull request merged**
